"""
v5 stage 2 — train the style planner.

Pipeline:
  1. Load stage 1 checkpoint (transformer + per-phoneme style encoder + style codebook).
     Freeze them. They produce GROUND-TRUTH style code sequences for each utterance.
  2. For each batch, encode the utterance through the frozen style encoder + codebook
     to get the target codes (B, N).
  3. Train the planner: predict those codes from (phoneme_ids, speaker, knobs).
     Loss = CE per phoneme position over style_codebook_size.

The dataset surfaces (emotion_id, style_id, intensity) per utterance from the
metadata file (utterance_metadata_v5.json — generated by HuBERT preprocessing).
If metadata is missing, defaults are (neutral, default, 1.0) which makes the
planner essentially predict an "average" prosody — usable but not knob-controllable.

Stage 2 is much cheaper than stage 1: planner is ~2M params, just CE on a small
codebook, no audio decoding. ~2-4 hours on MPS.
"""
import argparse
import math
import sys
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, random_split
from tqdm import tqdm

sys.path.insert(0, str(Path(__file__).parent.parent))

from models.transformer_rvq_hier import ArticulatoryTTSModelRVQHier
from models.per_phoneme_style_encoder import PerPhonemeStyleEncoder
from models.style_codebook import StyleCodebook, PAD_CODE
from models.style_planner import StylePlanner
from models.phoneme_vocab import PhonemeVocab
from training.dataset_rvq import (
    TTSDatasetRVQ, collate_tts_rvq, BucketBatchSampler,
    N_EMOTIONS, N_STYLES,
)
from training.metrics_logger import MetricsLogger, codebook_usage


def train(args):
    device = torch.device(args.device)
    print(f"v5 stage 2 (planner) — training on {device}")

    vocab = PhonemeVocab(args.vocab_path)
    print(f"Vocabulary: {len(vocab)} tokens")

    # ─── Load FROZEN stage-1 modules ─────────────────────
    s1_ckpt = torch.load(args.stage1_checkpoint, map_location=device, weights_only=True)
    sa = s1_ckpt["args"]
    print(f"Loaded stage1 checkpoint: epoch={s1_ckpt['epoch']}, val_loss={s1_ckpt['val_loss']:.4f}")

    style_encoder = PerPhonemeStyleEncoder(
        input_dim=14, style_dim=sa["d_model"], hidden=128, n_conv_layers=3,
    ).to(device)
    style_encoder.load_state_dict(s1_ckpt["style_encoder_state_dict"])
    style_encoder.eval()
    for p in style_encoder.parameters():
        p.requires_grad = False

    style_codebook = StyleCodebook(
        latent_dim=sa["d_model"], codebook_size=sa["style_codebook_size"],
    ).to(device)
    style_codebook.load_state_dict(s1_ckpt["style_codebook_state_dict"])
    style_codebook.eval()
    for p in style_codebook.parameters():
        p.requires_grad = False

    # ─── Build planner ───────────────────────────────────
    planner = StylePlanner(
        vocab_size=len(vocab),
        style_codebook_size=sa["style_codebook_size"],
        n_emotions=N_EMOTIONS,
        n_styles=N_STYLES,
        speaker_emb_dim=64,
        d_model=args.d_model,
        nhead=args.nhead,
        num_encoder_layers=args.num_layers,
        num_decoder_layers=args.num_layers,
        d_ff=args.d_ff,
        dropout=args.dropout,
        knob_dropout=args.knob_dropout,
    ).to(device)
    n_params = sum(p.numel() for p in planner.parameters())
    print(f"Planner params: {n_params:,}")

    # ─── Dataset ─────────────────────────────────────────
    dataset = TTSDatasetRVQ(
        features_dir=sa["features_dir"], phonemes_path=sa["phonemes_path"],
        alignments_path=sa["alignments_path"], vq_tokens_dir=sa["vq_tokens_dir"],
        vocab_path=args.vocab_path, preload=args.preload, max_frames=sa["max_frames"],
        metadata_path=args.metadata_path,
    )
    val_size = max(1, int(len(dataset) * 0.1))
    train_size = len(dataset) - val_size
    train_set, val_set = random_split(
        dataset, [train_size, val_size], generator=torch.Generator().manual_seed(42),
    )
    train_sampler = BucketBatchSampler(train_set, batch_size=args.batch_size, shuffle=True)
    train_loader = DataLoader(train_set, batch_sampler=train_sampler,
                              collate_fn=collate_tts_rvq, num_workers=0)
    val_loader = DataLoader(val_set, batch_size=args.batch_size, shuffle=False,
                            collate_fn=collate_tts_rvq, num_workers=0)

    optimizer = torch.optim.AdamW(planner.parameters(), lr=args.lr, weight_decay=args.weight_decay)
    total_steps = len(train_loader) * args.epochs
    def lr_lambda(step):
        if step < args.warmup_steps:
            return step / max(1, args.warmup_steps)
        progress = (step - args.warmup_steps) / max(1, total_steps - args.warmup_steps)
        return 0.5 * (1 + math.cos(progress * math.pi))
    scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer, lr_lambda)

    ckpt_dir = Path(args.checkpoint_dir)
    ckpt_dir.mkdir(parents=True, exist_ok=True)
    metrics = MetricsLogger(log_path=ckpt_dir / "metrics.jsonl",
                            grad_ratio_every=0,    # single-loss stage; no grad-ratio bookkeeping
                            scalar_every=100)

    best_val_loss = float("inf")
    start_epoch = 1
    global_step = 0

    if args.resume and (ckpt_dir / "planner_best.pt").exists():
        print(f"Resuming planner from {ckpt_dir / 'planner_best.pt'}")
        ckpt = torch.load(ckpt_dir / "planner_best.pt", map_location=device, weights_only=True)
        planner.load_state_dict(ckpt["planner_state_dict"])
        best_val_loss = ckpt.get("val_loss", float("inf"))
        start_epoch = ckpt.get("epoch", 0) + 1
        if args.restore_optim and "optimizer_state_dict" in ckpt:
            optimizer.load_state_dict(ckpt["optimizer_state_dict"])
            scheduler.load_state_dict(ckpt["scheduler_state_dict"])
            global_step = ckpt.get("global_step", 0)

    # ─── train loop ──────────────────────────────────────
    for epoch in range(start_epoch, args.epochs + 1):
        planner.train()
        metrics.epoch_start(epoch=epoch)
        agg = dict(loss=0.0, acc=0.0)
        n_batches = 0

        for batch in tqdm(train_loader, desc=f"Epoch {epoch}/{args.epochs}", leave=False):
            phoneme_ids = batch["phoneme_ids"].to(device)
            phoneme_mask = batch["phoneme_mask"].to(device)
            durations = batch["durations"].to(device)
            speaker_emb = batch["speaker_embs"].to(device)
            style_feats = batch["style_features"].to(device)
            emotion_id = batch["emotion_ids"].to(device)
            style_id   = batch["style_ids"].to(device)
            intensity  = batch["intensities"].to(device)

            # Generate target codes from frozen stage-1 (no grad)
            with torch.no_grad():
                z = style_encoder(style_feats, durations, phoneme_mask)
                _, target_codes, _ = style_codebook(z, phoneme_mask)
                # PAD_CODE positions will be filtered from the loss

            # Planner forward (teacher-forced)
            out = planner(phoneme_ids, phoneme_mask, speaker_emb,
                          emotion_id, style_id, intensity, target_codes=target_codes)
            logits = out["logits"]                # (B, N, codebook_size)
            B, N, C = logits.shape

            # CE loss, ignoring PAD_CODE positions
            tgt = target_codes
            valid = (tgt != PAD_CODE) & phoneme_mask
            if valid.sum() == 0:
                continue
            ce = F.cross_entropy(
                logits.reshape(-1, C),
                tgt.clamp(min=0).reshape(-1),
                reduction="none",
            ).reshape(B, N)
            loss = (ce * valid.float()).sum() / valid.float().sum().clamp(min=1)

            # Per-position accuracy on valid positions
            pred = logits.argmax(dim=-1)
            correct = ((pred == tgt) & valid).float().sum() / valid.float().sum().clamp(min=1)

            optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(planner.parameters(), 1.0)
            optimizer.step(); scheduler.step(); global_step += 1

            agg["loss"] += loss.item(); agg["acc"] += correct.item()
            n_batches += 1

            metrics.step(
                step=global_step, lr=optimizer.param_groups[0]["lr"],
                losses={"ce": loss.item()},
                extras={"acc": correct.item()},
            )

        # ─── validation ──────────────────────────────────
        planner.eval()
        val_loss_sum = 0.0; val_acc_sum = 0.0; vn = 0
        per_emotion_loss = {i: [] for i in range(N_EMOTIONS)}

        with torch.no_grad():
            for batch in val_loader:
                phoneme_ids = batch["phoneme_ids"].to(device)
                phoneme_mask = batch["phoneme_mask"].to(device)
                durations = batch["durations"].to(device)
                speaker_emb = batch["speaker_embs"].to(device)
                style_feats = batch["style_features"].to(device)
                emotion_id = batch["emotion_ids"].to(device)
                style_id   = batch["style_ids"].to(device)
                intensity  = batch["intensities"].to(device)

                z = style_encoder(style_feats, durations, phoneme_mask)
                _, target_codes, _ = style_codebook(z, phoneme_mask)

                out = planner(phoneme_ids, phoneme_mask, speaker_emb,
                              emotion_id, style_id, intensity, target_codes=target_codes)
                logits = out["logits"]
                B, N, C = logits.shape
                valid = (target_codes != PAD_CODE) & phoneme_mask
                if valid.sum() == 0: continue
                ce = F.cross_entropy(logits.reshape(-1, C),
                                     target_codes.clamp(min=0).reshape(-1),
                                     reduction="none").reshape(B, N)
                loss = (ce * valid.float()).sum() / valid.float().sum().clamp(min=1)
                pred = logits.argmax(dim=-1)
                correct = ((pred == target_codes) & valid).float().sum() / valid.float().sum().clamp(min=1)
                val_loss_sum += loss.item(); val_acc_sum += correct.item(); vn += 1

                # Per-emotion CE breakdown
                for ei in range(N_EMOTIONS):
                    ei_mask = (emotion_id == ei).unsqueeze(-1).expand(-1, N) & valid
                    if ei_mask.sum() > 0:
                        ei_loss = (ce * ei_mask.float()).sum() / ei_mask.float().sum().clamp(min=1)
                        per_emotion_loss[ei].append(ei_loss.item())

        train_metrics = {"ce": agg["loss"] / max(1, n_batches),
                         "acc": agg["acc"] / max(1, n_batches)}
        val_metrics = {
            "ce": val_loss_sum / max(1, vn),
            "acc": val_acc_sum / max(1, vn),
            "perplexity": math.exp(val_loss_sum / max(1, vn)),
            **{f"ce_emotion_{ei}": (sum(v)/len(v) if v else 0.0)
               for ei, v in per_emotion_loss.items()},
        }
        print(f"Epoch {epoch:3d} | train CE={train_metrics['ce']:.4f} acc={train_metrics['acc']:.1%} | "
              f"val CE={val_metrics['ce']:.4f} acc={val_metrics['acc']:.1%} "
              f"ppx={val_metrics['perplexity']:.1f}")

        if val_metrics["ce"] < best_val_loss:
            best_val_loss = val_metrics["ce"]
            torch.save({
                "epoch": epoch,
                "planner_state_dict": planner.state_dict(),
                "optimizer_state_dict": optimizer.state_dict(),
                "scheduler_state_dict": scheduler.state_dict(),
                "global_step": global_step,
                "val_loss": best_val_loss,
                "args": vars(args),
                "stage1_args": sa,
            }, ckpt_dir / "planner_best.pt")
            print(f"  -> Saved best (val CE={best_val_loss:.4f})")

        metrics.epoch_end(epoch=epoch, train_metrics=train_metrics,
                          val_metrics=val_metrics, best_val_loss=best_val_loss)

    metrics.close()
    print(f"\nStage 2 training complete. Best val CE: {best_val_loss:.4f}")


if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--stage1-checkpoint", type=str,
                   default="checkpoints_v5_stage1/transformer_best.pt")
    p.add_argument("--vocab-path", type=str, default="data/processed_all/vocab_mfa.json")
    p.add_argument("--metadata-path", type=str, default="data/utterance_metadata_v5.json")
    p.add_argument("--checkpoint-dir", type=str, default="checkpoints_v5_planner")
    p.add_argument("--device", type=str, default="mps")
    p.add_argument("--batch-size", type=int, default=32)
    p.add_argument("--epochs", type=int, default=20)
    p.add_argument("--lr", type=float, default=5e-4)
    p.add_argument("--weight-decay", type=float, default=0.01)
    p.add_argument("--warmup-steps", type=int, default=500)
    p.add_argument("--d-model", type=int, default=128)
    p.add_argument("--nhead", type=int, default=4)
    p.add_argument("--num-layers", type=int, default=4)
    p.add_argument("--d-ff", type=int, default=512)
    p.add_argument("--dropout", type=float, default=0.1)
    p.add_argument("--knob-dropout", type=float, default=0.1,
                   help="Random knob-dropout rate at training; encourages text-only generalization")
    p.add_argument("--preload", action="store_true")
    p.add_argument("--resume", action="store_true")
    p.add_argument("--restore-optim", action="store_true", default=True)
    args = p.parse_args()
    train(args)
